#!/bin/bash
# Script Name: neoagland.sh
# Description: Run the neoantigen landscape construction
# Author: Kohan

### Input Arguments
usage() {
  cat <<EOF 
Usage: $(basename "${BASH_SOURCE[0]}") <args>

This script runs the neoantigen landscape construction

Available options:
-i  Neoantigen prediction file from neoagfinder.sh [REQUIRED]
-c  Cluster file generated by PyClone [REQUIRED]
-l  Loci file generated by PyClone [REQUIRED]
-o  Output path [REQUIRED]
EOF
  exit
}

while getopts "i:c:l:o:h" opt; do
    case "${opt}" in
        i) INPUT=${OPTARG};;
        c) CLUSTER_FILE=${OPTARG};;
        l) LOCI_FILE=${OPTARG};;
        o) OUTPUT=${OPTARG};;
        h) usage;;
    esac
done

if [ -z "${INPUT}" ] || [ -z "${CLUSTER_FILE}" ] || [ -z "${LOCI_FILE}" ] || [ -z "${OUTPUT}" ]; then
    usage
fi

if [ ! -f "${INPUT}" ]; then
    echo "Error: The file ${INPUT} does not exist."
    exit 1
fi

if [ ! -f "${CLUSTER_FILE}" ]; then
    echo "Error: The file ${CLUSTER_FILE} does not exist."
    exit 1
fi

if [ ! -f "${LOCI_FILE}" ]; then
    echo "Error: The file ${LOCI_FILE} does not exist."
    exit 1
fi

echo "
#####################################
#####           Paths           #####
#####################################
"
echo "Input file: ${INPUT}"
echo "Cluster file: ${CLUSTER_FILE}"
echo "Loci file: ${LOCI_FILE}"
echo "Ouput file: ${OUTPUT}"
echo

# Assign variables
REAL_PATH=$(realpath $0)
SRC_DIR=$(dirname ${REAL_PATH})
SRC_DIR=${SRC_DIR}/neoprecis

### NP-Landscape calculation
echo "
#####################################
##### NP-Landscape Calculation  #####
#####################################
"
echo "Constructing neoantigen landscape ..."
python3 "${SRC_DIR}/construct_landscape.py" \
    "${INPUT}" \
    "${CLUSTER_FILE}" \
    "${LOCI_FILE}" \
    "${OUTPUT}" \
    --rank_ref "${SRC_DIR}/landscape_rank_ref.csv"
echo